CREATE DATABASE HOISV

ON PRIMARY 
(
	NAME ='QLHOISV',
	FILENAME ='T:\23709281_NguyenTanHung\QLHOISV.mdf'
)
LOG ON
(
	NAME ='QLHOISV_LOG',
	FILENAME ='T:\23709281_NguyenTanHung\QLHOISV_LOG.Ldf'
)

USE HOISV

ALTER DATABASE HOISV
ADD GROUPFILE
EXEC sp_helpfile